/**
 * 音素
 */
const symbols = new Map()

symbols.set('iː', 1)
symbols.set('ɪ', 2)
symbols.set('e', 3)
symbols.set('æ', 4)
symbols.set('ɑː', 5)
symbols.set('ɒ', 6)
symbols.set('ɔː', 7)
symbols.set('ʊ', 8)
symbols.set('uː', 9)
symbols.set('ʌ', 10)
symbols.set('ɜː', 11)
symbols.set('ә', 12)
symbols.set('eɪ', 13)
symbols.set('әʊ', 14)
symbols.set('aɪ', 15)
symbols.set('aʊ', 16)
symbols.set('ɔɪ', 17)
symbols.set('ɪə', 18)
symbols.set('eə', 19)
symbols.set('ʊə', 20)
symbols.set('p', 21)
symbols.set('b', 22)
symbols.set('t', 23)
symbols.set('d', 24)
symbols.set('k', 25)
symbols.set('g', 26)
symbols.set('f', 27)
symbols.set('θ', 28)
symbols.set('h', 29)
symbols.set('ð', 30)
symbols.set('s', 31)
symbols.set('ʃ', 32)
symbols.set('z', 33)
symbols.set('v', 34)
symbols.set('ʒ', 35)
symbols.set('r', 36)
symbols.set('tʃ', 37)
symbols.set('dʒ', 38)
symbols.set('tr', 39)
symbols.set('dr', 40)
symbols.set('ts', 41)
symbols.set('dz', 42)
symbols.set('m', 43)
symbols.set('n', 44)
symbols.set('ŋ', 45)
symbols.set('l', 46)
symbols.set('w', 47)
symbols.set('j', 48)

export default symbols
